############################
## CHANGE THESE
############################

baseURL: "https://betapr0x.github.io/jsc"
title: jsc

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
